pipeline:
  name: lambdaCodeZIPS3
  identifier: lambdaCodeZIPS3
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: testinglambda
        build: <+input>
  stages:
    - stage:
        name: GithucCloneCode
        identifier: GithucCloneCode
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: upload to s3
                  identifier: upload_to_s3
                  spec:
                    shell: Sh
                    command: "aws configure set aws_access_key_id AKIA5U3R675QNZZ2AJET\r\naws configure set aws_secret_access_key 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 \r\n#zip -r test.zip .\r\naws s3 sync . s3://lambdaexecutionbucket1"
