pipeline:
  name: LambdatedtingZIP
  identifier: LambdatedtingZIP
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Github
        repoName: testinglambda
        build: <+input>
  stages:
    - stage:
        name: gitlcone
        identifier: gitlcone
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: "pwd \r\nls\r\nrm -f testinglambda\r\n"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
