pipeline:
  name: testinglambdazipcode
  identifier: testinglambdazipcode
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: testinglambda
        build: <+input>
  stages:
    - stage:
        name: gitclonecode
        identifier: gitclonecode
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: CompressFile
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo "INFO: Compress file"
                      zip -r refdata.zip testinglambda/
                      ls

                       
              - step:
                  type: Run
                  name: Upload Artifact to s3
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      aws configure set aws_access_key_id <+pipeline.variables.Accesskey>
                      aws configure set aws_secret_access_key <+pipeline.variables.Secretkey>
                      aws s3 cp refdata.zip s3://lambdaexecutionbucket1/refdata.zip
              - step:
                  type: Run
                  name: "UpdateLambdaFucntion "
                  identifier: UpdateLambdaFucntion
                  spec:
                    shell: Sh
                    command: "aws configure set aws_access_key_id <+pipeline.variables.Accesskey>\r\naws configure set aws_secret_access_key <+pipeline.variables.Secretkey>\r\naws lambda update-function-code --function-name lambdaexampletesting56789t --s3-bucket lambdaexecutionbucket1 --s3-key test.zip --region us-east-2"
  variables:
    - name: Accesskey
      type: Secret
      description: ""
      required: false
      value: Accesskey
    - name: Secretkey
      type: Secret
      description: ""
      required: false
      value: Secretkey
